server:
  port: 8501
spring:
  application:
    name: account-service
  zipkin:
    base-url: http://localhost:9411/
  data:
    cassandra:
      contact-points: localhost
      keyspace-name: spring_cloud
      password: cassandra
      username: cassandra
      port: 9042

  boot:
    admin:
      client:
        url: http://localhost:8508
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/