server:
  port: 8501
spring:
  application:
    name: account-service
  data:
    cassandra:
      contact-points: localhost
      keyspace-name: spring_cloud
      password: cassandra
      username: cassandra
      port: 9042
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/