server:
  port: 8503

spring:
  application:
    name: notification-service
  rabbitmq:
    username: someuser
    password: someuser

  cloud:
    stream:
      bindings:
        input:
          destination: msqueue
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/