version: '3.1'

services:
  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: microservice-app
    ports:
      - '3306:3306'
  elasticsearch:
    image: elasticsearch:6.8.5
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - discovery.type=single-node


  msrabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672' # docker rabbit
      - '15672:15672' # rabbit uı
    environment:
      - RABBITMQ_DEFAULT_USER=azad1223
      - RABBITMQ_DEFAULT_PASS=azad1223
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411

